name: "r2devops"

x-jobs-common: &jobs-common
    image: docker.io/r2devopsio/jobs:$BACKEND_IMAGE_TAG
    env_file: .env
    environment:
      - JOBS_LISTEN_ADDR=0.0.0.0
      - JOBS_LISTEN_PORT=3000
      - JOBS_CORS_ORIGIN=http://$FRONTEND_DOMAIN
      - JOBS_FRONTEND_URL=http://$FRONTEND_DOMAIN
      - JOBS_SESSION_TTL=168h
      - JOBS_DB_HOST=postgres
      - JOBS_DB_PORT=5432
      - JOBS_DB_SSLMODE=disable
      - JOBS_DB_TIMEZONE=Europe/Paris
      - JOBS_API_DOMAIN=$API_DOMAIN$API_PATH
      - LOG_LEVEL=info
      - LOG_FORMATTER=text
      - JOBS_REDIS_HOST=redis
      - JOBS_REDIS_PORT=6379
      - JOBS_REDIS_DB=0
      - JOBS_REDIS_USER=default
      - JOBS_REDIS_SET_NAMESPACES_TTL=30s
      - GITLEAKS_PATH=/opt/gitleaks
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    networks:
      - intranet

services:

  ############
  # R2Devops #
  ############

  frontend:
    image: docker.io/r2devopsio/frontend:$FRONTEND_IMAGE_TAG
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    ports:
      - "3000:3000"
    networks:
      - intranet

  jobs:
    <<: *jobs-common
    command: ["/bin/sh", "-c", "sleep 10 && ./app"]
    ports:
      - "3001:3000"

  jobs_worker:
    <<: *jobs-common
    command: ["/bin/sh", "-c", "sleep 15 && ./app --worker"]
    deploy:
      mode: replicated
      replicas: 5


  #####################
  # External services #
  #####################

  redis:
    image: redis:7.4.5
    restart: unless-stopped
    env_file: .env
    command:
      - redis-server
      - --requirepass $JOBS_REDIS_PASSWORD
    expose:
      - "6379"
    networks:
      - intranet

  postgres:
    image: postgres:13.21
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$JOBS_DB_USER
      - POSTGRES_PASSWORD=$JOBS_DB_PASSWORD
      - POSTGRES_DB=$JOBS_DB_NAME
    expose:
      - "5432"
    networks:
      - intranet
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  intranet:

volumes:
  postgres-data:
