name: "r2devops"

x-jobs-common: &jobs-common
    image: docker.io/r2devopsio/jobs:$BACKEND_IMAGE_TAG
    env_file: .env
    environment:
      - JOBS_LISTEN_ADDR=0.0.0.0
      - JOBS_LISTEN_PORT=80
      - JOBS_CORS_ORIGIN=https://$DOMAIN_NAME
      - JOBS_FRONTEND_URL=https://$DOMAIN_NAME
      - JOBS_SESSION_TTL=168h
      - JOBS_API_DOMAIN=https://$API_URL
      - LOG_LEVEL=info
      - LOG_FORMATTER=text
      - JOBS_REDIS_HOST=redis
      - JOBS_REDIS_PORT=6379
      - JOBS_REDIS_DB=0
      - JOBS_REDIS_USER=default
      - JOBS_REDIS_SET_NAMESPACES_TTL=30s
      - GITLEAKS_PATH=/opt/gitleaks
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    networks:
      - intranet

services:

  ############
  # R2Devops #
  ############

  frontend:
    image: docker.io/r2devopsio/frontend:$FRONTEND_IMAGE_TAG
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.front.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=le"
    networks:
      - intranet

  jobs:
    <<: *jobs-common
    expose:
      - "80"
      - "9090"
    labels:
      - "traefik.http.routers.api.rule=Host(\"$API_DOMAIN\")&&PathPrefix(\"$API_PATH\")"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"

  jobs_worker:
    <<: *jobs-common
    command: ["--worker"]
    deploy:
      mode: replicated
      replicas: 5
    expose:
      - "9090"
    labels:
      - "traefik.enable=false"


  #####################
  # External services #
  #####################

  redis:
    image: redis:8.4
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    command:
      - redis-server
      - --requirepass $JOBS_REDIS_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$$JOBS_REDIS_PASSWORD\" ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    expose:
      - "6379"
    networks:
      - intranet


  #################
  # Reverse proxy #
  #################

  traefik:
    image: traefik:3.6
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - frontend
      - jobs
    ports:
      - "80:80"
      - "443:443"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-acme:/acme
    networks:
      - intranet

networks:
  intranet:

volumes:
  postgres-data:
  traefik-acme:
