version: '3.9'
name: "r2devops"

x-jobs-common: &jobs-common
    image: docker.io/r2devopsio/jobs:$BACKEND_IMAGE_TAG
    env_file: .env
    environment:
      - JOBS_LISTEN_ADDR=0.0.0.0
      - JOBS_LISTEN_PORT=80
      - JOBS_CORS_ORIGIN=https://$DOMAIN_NAME
      - JOBS_FRONTEND_URL=https://$DOMAIN_NAME
      - JOBS_SESSION_TTL=168h
      - JOBS_API_DOMAIN=https://$API_URL
      - LOG_LEVEL=info
      - LOG_FORMATTER=text
      - S3_HOST=minio:9000
      - S3_REGION=us-east-1
      - S3_DISABLE_SSL=true
      - S3_FORCE_PATH_STYLE=true
      - JOBS_REDIS_HOST=redis
      - JOBS_REDIS_PORT=6379
      - JOBS_REDIS_DB=0
      - JOBS_REDIS_USER=default
      - JOBS_REDIS_SET_NAMESPACES_TTL=120h
      - GITLEAKS_PATH="/opt/gitleaks"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    networks:
      - intranet

services:

  ############
  # R2Devops #
  ############

  frontend:
    image: docker.io/r2devopsio/frontend:$FRONTEND_IMAGE_TAG
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./.docker/r2devops/config.json
        target: /app/.next/server/app/config.body
      - ./.docker/ca-certificates:/usr/local/share/ca-certificates/
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.front.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
    networks:
      - intranet

  jobs:
    <<: *jobs-common
    command: ["/bin/sh", "-c", "sleep 10 && ./app"]
    expose:
      - "80"
    labels:
      - "traefik.http.routers.api.rule=Host(\"$API_DOMAIN\")&&PathPrefix(\"$API_PATH\")"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"

  jobs_worker:
    <<: *jobs-common
    command: ["/bin/sh", "-c", "sleep 15 && ./app --worker"]
    deploy:
      mode: replicated
      replicas: 30
    labels:
      - "traefik.enable=false"


  #####################
  # External services #
  #####################

  redis:
    image: redis:6
    restart: unless-stopped
    env_file:
      - .env
    command:
      - redis-server
      - --requirepass $JOBS_REDIS_PASSWORD
    expose:
      - "6379"
    networks:
      - intranet

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$JOBS_DB_USER
      - POSTGRES_PASSWORD=$JOBS_DB_PASSWORD
      - POSTGRES_DB=$JOBS_DB_NAME
    expose:
      - "5432"
    networks:
      - intranet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=$S3_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=$S3_SECRET_KEY
      - MINIO_BUCKET=$S3_BUCKET
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio-data:/export
      - minio-data_config:/root/.minio
    command: server /export
    labels:
      - "traefik.enable=false"
    networks:
      - intranet


  #################
  # Reverse proxy #
  #################

  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    depends_on:
      - frontend
      - jobs
    ports:
      - "80:80"
      - "443:443"
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/certs.yml
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/traefik/certs:/certs
      - ./.docker/traefik/certs.yml:/etc/traefik/certs.yml
    networks:
      - intranet

networks:
  intranet:

volumes:
  minio-data:
  minio-data_config:
  postgres-data:
