global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'jobs'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        filters:
          - name: "label"
            values: ["com.docker.compose.service=jobs"]
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      # Filtler to keep only port 9090
      - source_labels: [__meta_docker_port_private]
        regex: "9090"
        action: keep
      # Use the container name instead of IP
      - source_labels: [__meta_docker_container_name]
        target_label: instance

  - job_name: 'jobs_worker'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        filters:
          - name: "label"
            values: ["com.docker.compose.service=jobs_worker"]
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      # Filtler to keep only port 9090
      - source_labels: [__meta_docker_port_private]
        regex: "9090"
        action: keep
      # Use the container name instead of IP
      - source_labels: [__meta_docker_container_name]
        target_label: instance
