name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  code-analysis:
    name: Code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.10.1
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.11
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - name: Add dependency chart repositories
        run: ./scripts/add_helm_repo.sh
      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi
      - name: Lint charts
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: d3adb5/helm-unittest-action@v2
        with:
          charts: charts/r2devops
          flags: --color -o test-results.xml --output-type JUnit
          helm-version: v3.10.1
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}   # run this step even if previous step failed
        with:
          name: Helm Unit Tests   # Name of the check run which will be created
          path: test-results.xml  # Path to test results
          reporter: java-junit    # Format of test results

